### ISSUE TITLE
Remove dev dependencies from requirements.txt

### ISSUE THREAD

**Issue by franklinselva** [kadirnar/strongsort-pip#1]
Hi,

Setting up PyPi releases for `strong_sort` is really helpful. Thank you for starting it out.

I found that in version `0.2.0`, there are dev dependencies as part of `requirements.txt`. I am not sure if it is helpful to the library itself. I would like to check with you for removing the possibility the unnecessary packages from the release version.

**Comment by kadirnar** [comment]
Hello @franklinselva 

Thank you for your interest in the library. Are you referring to the Black and Isort libraries?

**Comment by franklinselva** [comment]
Yes. I am. Could we remove these packages from library dependencies? If needed, I could also contribute to the package.

**Comment by kadirnar** [comment]
That would be great. If you open a Pull Request I can accept it. You can make this change to other repos as well.

https://github.com/kadirnar/TrackerHub
https://github.com/kadirnar/ocsort-pip
https://github.com/kadirnar/sort-pip
https://github.com/kadirnar/bytetrack-pip

**Comment by franklinselva** [comment]
Thank you. I will check with your other works too. I will add a PR for the new changes.
